# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAjqyax7Z8aSo2p9DH4AP64B0GZI7P6T
"""

# 印出歡迎訊息
print("歡迎使用足球賽況紀錄器！")

# 詢問使用者主隊名稱並儲存
home_team = input("主隊名稱 (Home Team) 是？ ")

# 詢問使用者客隊名稱並儲存
away_team = input("客隊名稱 (Away Team) 是？ ")

# 建立一個空的列表，用來稍後儲存所有進球紀錄
match_events = []

# 印出比賽開始訊息
print("比賽開始！等待指令中...")

# 使用無窮迴圈讓程式持續執行，直到使用者輸入 'end'
while True:
    # 詢問使用者輸入指令
    command = input("請輸入指令 (goal / end)： ")

    # 判斷使用者輸入的指令
    if command == "end":
        # 如果是 'end'，印出比賽結束訊息並跳出迴圈
        print("比賽結束")
        break
    elif command == "goal":
        # 如果是 'goal'，印出準備紀錄進球的訊息
        print("準備紀錄進球...")

        # 詢問進球球隊
        team_choice = input("進球球隊 (1 代表主隊, 2 代表客隊)： ")
        team_name = ""
        if team_choice == "1":
            team_name = home_team
        elif team_choice == "2":
            team_name = away_team
        else:
            print("無效的球隊選擇，請重新輸入指令。")
            continue # 跳過本次迴圈，重新詢問指令

        # 詢問進球時間
        try:
            goal_time = int(input("進球時間 (第幾分鐘?)： "))
        except ValueError:
            print("時間輸入無效，請輸入數字。請重新輸入指令。")
            continue # 跳過本次迴迴圈，重新詢問指令

        # 詢問進球區域
        goal_zone = input("進球區域 (左路/中路/右路/定位球)： ")

        # 詢問進球方式
        goal_type = input("進球方式 (射門/頭槌/點球)： ")

        # 新增詢問得分球員
        scorer = input("得分球員 (人名/球衣號碼)： ")

        # 新增詢問助攻球員
        assist_player = input("助攻球員 (人名/球衣號碼/無)： ")

        # 將進球資訊包裝成字典
        goal_event = {
            'team': team_name,
            'time': goal_time,
            'zone': goal_zone,
            'type': goal_type,
            'scorer': scorer,
            'assist': assist_player
        }

        # 將字典加入 match_events 列表中
        match_events.append(goal_event)

        # 印出紀錄成功訊息
        print("紀錄成功！")

        # 每次紀錄成功後，顯示目前比分和進球紀錄
        current_home_score = 0
        current_away_score = 0
        for event in match_events:
            if event['team'] == home_team:
                current_home_score += 1
            elif event['team'] == away_team:
                current_away_score += 1

        print("\n--- 目前比分 ---")
        print(f"{home_team} {current_home_score} : {current_away_score} {away_team}")

        print("\n--- 進球紀錄 ---")
        if not match_events:
            print("本場比賽沒有進球紀錄。")
        else:
            for event in match_events:
                print(f"第 {event['time']} 分鐘 - [{event['team']}] - {event['zone']} - {event['type']} - 進球者: {event['scorer']} - 助攻者: {event['assist']}")

    else:
        # 如果是其他指令，印出錯誤訊息
        print("指令錯誤，請重新輸入")

# 比賽結束後的最終統計 (當break跳出迴圈時執行)
final_home_score = 0
final_away_score = 0

for event in match_events:
    if event['team'] == home_team:
        final_home_score += 1
    elif event['team'] == away_team:
        final_away_score += 1

print("\n--- 最終比分 ---")
print(f"{home_team} {final_home_score} : {final_away_score} {away_team}")

print("\n--- 最終進球紀錄 ---")
if not match_events:
    print("本場比賽沒有進球紀錄。")
else:
    for event in match_events:
        print(f"第 {event['time']} 分鐘 - [{event['team']}] - {event['zone']} - {event['type']} - 進球者: {event['scorer']} - 助攻者: {event['assist']}")