# -*- coding: utf-8 -*-
"""⚽足球賽況記錄器

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQAdXia6WQPs7tOa4wMqAHh_0638BsYB
"""

import streamlit as st
import pandas as pd # 引入 pandas 是為了讓 dataframe顯示更漂亮

# ==============================================================================
# 1. [狀態保存] 初始化狀態
# Streamlit 每次互動都會重跑程式，所以必須檢查 session_state 是否已存在資料
# ==============================================================================

# 初始化事件列表：這是我們的小型資料庫，存在記憶體中
if 'events' not in st.session_state:
    st.session_state['events'] = [] # [狀態保存] 這裡建立空列表，確保重跑時資料不會消失

# 初始化隊伍名稱預設值
if 'home_team' not in st.session_state:
    st.session_state['home_team'] = "主隊"
if 'away_team' not in st.session_state:
    st.session_state['away_team'] = "客隊"

# ==============================================================================
# 2. 介面標題
# ==============================================================================
st.title("⚽ 足球賽況記錄器")

# ==============================================================================
# 3. 側邊欄：隊伍設定 & 進球紀錄表單
# ==============================================================================
with st.sidebar:
    st.header("1. 隊伍設定")
    # [狀態保存] 使用 key 參數將輸入框直接綁定到 session_state
    home_name = st.text_input("主隊名稱", key='home_team')
    away_name = st.text_input("客隊名稱", key='away_team')

    st.divider() # 分隔線

    st.header("2. 紀錄操作")

    # 建立一個可折疊的區塊 (Expander)
    with st.expander("紀錄進球", expanded=True):

        # --- 表單輸入元件 ---
        # 選項會隨著上面的隊伍名稱動態改變
        team_input = st.radio("進球球隊", [home_name, away_name])

        time_input = st.number_input("進球時間 (分鐘)", min_value=0, max_value=125, step=1)

        zone_input = st.selectbox("進球區域", ["左路", "中路", "右路", "定位球"])

        type_input = st.selectbox("進球方式", ["射門", "頭槌", "點球"])

        # 為了資料完整性，我保留了原本邏輯中的球員欄位
        scorer_input = st.text_input("得分球員")
        assist_input = st.text_input("助攻球員 (選填)", value="無")

        # --- [狀態保存] 寫入數據的核心邏輯 ---
        if st.button("確認進球"):
            # 1. 將收集到的變數包裝成字典 (Dictionary)
            new_event = {
                'team': team_input,
                'time': time_input,
                'zone': zone_input,
                'type': type_input,
                'scorer': scorer_input,
                'assist': assist_input
            }

            # 2. [狀態保存] 將字典 append 到 session_state['events'] 列表中
            st.session_state['events'].append(new_event)

            # 3. 顯示成功訊息 (會短暫顯示)
            st.success(f"已紀錄：{time_input}' {team_input} 進球！")

# ==============================================================================
# 4. 主畫面：顯示結果
# ==============================================================================

# 檢查是否有資料
if len(st.session_state['events']) > 0:
    st.subheader("📊 目前賽況紀錄")

    # [狀態保存] 從 session_state 中讀取所有資料並顯示
    # 使用 Pandas DataFrame 可以讓表格可以排序、放大
    df = pd.DataFrame(st.session_state['events'])

    # 調整欄位顯示順序（美觀用）
    st.dataframe(
        df,
        column_config={
            "team": "球隊",
            "time": "時間 (分)",
            "zone": "區域",
            "type": "方式",
            "scorer": "得分者",
            "assist": "助攻"
        },
        use_container_width=True
    )

    # 簡單顯示最新的一筆紀錄
    last_event = st.session_state['events'][-1]
    st.caption(f"最新動態：第 {last_event['time']} 分鐘，{last_event['scorer']} ({last_event['team']}) 得分。")

else:
    st.info("👈 請在側邊欄輸入隊伍名稱，並展開「紀錄進球」開始紀錄。")